package com.wanted.backend.global.domain;

public enum SubjectType {
    KO_READING, KO_LITERATURE, KO_SPEECH_WRITING, KO_LANGUAGE_MEDIA,
    MATH_1, MATH_2, MATH_PROB_STAT, MATH_CALCULUS, MATH_GEOMETRY,
    ENG_1, ENG_2,
    KOR_HISTORY,
    SO_LIFE_ETHICS, SO_ETHICS_THOUGHT, SO_KOREAN_GEOGRAPHY, SO_WORLD_GEOGRAPHY,
    SO_EAST_ASIAN_HISTORY, SO_WORLD_HISTORY, SO_ECONOMICS, SO_POLITICS_LAW, SO_CULTURE,
    SC_PHYSICS_1, SC_CHEMISTRY_1, SC_BIOLOGY_1, SC_EARTH_1,
    SC_PHYSICS_2, SC_CHEMISTRY_2, SC_BIOLOGY_2, SC_EARTH_2,
    FL_GERMAN, FL_FRENCH, FL_SPANISH, FL_CHINESE, FL_JAPANESE,
    FL_RUSSIAN, FL_ARABIC, FL_VIETNAMESE, FL_HANMUN
}