services:
  redis:
    image: redis:7
    container_name: hardclick-redis
    command: redis-server --requirepass hard_click_redis_2026
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  influxdb:
    image: influxdb:2
    container_name: hardclick-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  redis-data:
  influxdb-data: