spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: hard-click
    password: hard-click

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 테스트 환경에서는 파일에 로그를 남기지 않고 콘솔에만 찍도록 test 프로필 적용
logging:
  config: classpath:logback-spring.xml