spring:
  application:
    name: Hard-Click-BackEnd
#개발할 때 dev 테스트 할 때 test
  profiles:
    active: test

  config:
    import: optional:classpath:application-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Hard-Click
    username: Hard-Click
    password: Hard-Click

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:1209600000}