apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus_ds
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true

  - name: Loki
    uid: loki_ds
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
