CREATE TABLE IF NOT EXISTS course (
    course_id BIGINT NOT NULL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    thumbnail_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS course_section (
    id BIGINT NOT NULL PRIMARY KEY,
    course_id BIGINT NOT NULL,
    order_index INT NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT NOT NULL PRIMARY KEY,
    section_id BIGINT NOT NULL,
    order_index INT NOT NULL
);

CREATE TABLE IF NOT EXISTS video_progress (
    progress_id BIGINT NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    last_position_sec INT NOT NULL,
    is_completed TINYINT NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS enrollment (
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    enrolled_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    expired_at TIMESTAMP,
    CONSTRAINT uk_enrollment_member_course UNIQUE (member_id, course_id)
);
