CREATE TABLE IF NOT EXISTS courses (
    course_id BIGINT NOT NULL PRIMARY KEY,
    instructor_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    price INT NOT NULL,
    thumbnail_url VARCHAR(500),
    file_url VARCHAR(500),
    file_status VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    avg_rating DECIMAL(3, 1) NOT NULL,
    review_count INT NOT NULL,
    student_count INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS course_curriculum (
    curriculum_id BIGINT NOT NULL PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    duration_minutes INT,
    order_index INT NOT NULL
);

CREATE TABLE IF NOT EXISTS video (
    video_id BIGINT NOT NULL PRIMARY KEY,
    curriculum_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    video_url VARCHAR(500) NOT NULL,
    is_preview TINYINT NOT NULL,
    duration_seconds INT NOT NULL,
    sort_order INT NOT NULL
);

CREATE TABLE IF NOT EXISTS video_progress (
    progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    last_position_sec INT NOT NULL,
    watch_time_sec INT NOT NULL,
    is_completed TINYINT NOT NULL,
    completed_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS enrollments (
    enrollment_id BIGINT NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    progress_rate DECIMAL(5, 2) NOT NULL,
    expired_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriptions (
    subscription_id BIGINT NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    paid_amount INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS study_timer_sessions (
    study_timer_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT,
    lesson_id BIGINT,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    elapsed_seconds INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
