package com.wanted.backend.domain.identity.infrastructure.persistence;

import com.wanted.backend.domain.identity.domain.model.EmailPurpose;
import com.wanted.backend.domain.identity.domain.model.EmailVerification;
import com.wanted.backend.domain.identity.domain.repository.EmailVerificationRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.jdbc.Sql;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none"
})
@Import(EmailVerificationPersistenceAdapter.class)
class EmailVerificationPersistenceAdapterTest {

    @Autowired
    private EmailVerificationRepository emailVerificationRepository;

    @Sql(statements = {
            "drop table if exists email_verifications",
            "create table email_verifications (" +
                    "verification_id bigint generated by default as identity primary key, " +
                    "email varchar(100) not null, " +
                    "used boolean not null, " +
                    "code varchar(10) not null, " +
                    "purpose varchar(30) not null, " +
                    "is_verified boolean not null, " +
                    "verification_token varchar(200), " +
                    "expires_at timestamp not null, " +
                    "verified_at timestamp, " +
                    "created_at timestamp not null" +
                    ")"
    })
    @Test
    @DisplayName("이메일 인증 정보를 저장하고 최신 인증 정보를 도메인으로 조회한다")
    void saveAndFindLatest_success() {
        String email = "user@example.com";
        EmailPurpose purpose = EmailPurpose.ACCOUNT_LOCK;

        EmailVerification verification = EmailVerification.create(email, purpose);

        emailVerificationRepository.save(verification);

        EmailVerification found = emailVerificationRepository
                .findLatestByEmailAndPurpose(email, purpose)
                .orElseThrow();

        assertThat(found.getEmail()).isEqualTo(email);
        assertThat(found.getPurpose()).isEqualTo(purpose);
        assertThat(found.getCode()).isEqualTo(verification.getCode());
        assertThat(found.isVerified()).isFalse();
        assertThat(found.getExpiresAt()).isNotNull();
    }
}